CREATE TABLE IF NOT EXISTS paises (
  id INT AUTO_INCREMENT NOT NULL,
  codigo varchar(2) NOT NULL,
  nombre varchar(100) NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO paises (id, codigo, nombre) VALUES
(NULL, 'AU', 'Australia'),
(NULL, 'CN', 'China'),
(NULL, 'JP', 'Japan'),
(NULL, 'TH', 'Thailand'),
(NULL, 'IN', 'India'),
(NULL, 'MY', 'Malaysia'),
(NULL, 'KR', 'Kore'),
(NULL, 'HK', 'Hong Kong'),
(NULL, 'TW', 'Taiwan'),
(NULL, 'PH', 'Philippines'),
(NULL, 'VN', 'Vietnam'),
(NULL, 'FR', 'France'),
(NULL, 'EU', 'Europe'),
(NULL, 'DE', 'Germany'),
(NULL, 'SE', 'Sweden'),
(NULL, 'IT', 'Italy'),
(NULL, 'GR', 'Greece'),
(NULL, 'ES', 'Spain'),
(NULL, 'AT', 'Austria'),
(NULL, 'GB', 'United Kingdom'),
(NULL, 'NL', 'Netherlands'),
(NULL, 'BE', 'Belgium'),
(NULL, 'CH', 'Switzerland'),
(NULL, 'AE', 'United Arab Emirates'),
(NULL, 'IL', 'Israel'),
(NULL, 'UA', 'Ukraine'),
(NULL, 'RU', 'Russian Federation'),
(NULL, 'KZ', 'Kazakhstan'),
(NULL, 'PT', 'Portugal'),
(NULL, 'SA', 'Saudi Arabia'),
(NULL, 'DK', 'Denmark'),
(NULL, 'IR', 'Ira'),
(NULL, 'NO', 'Norway'),
(NULL, 'US', 'United States'),
(NULL, 'MX', 'Mexico'),
(NULL, 'CA', 'Canada'),
(NULL, 'A1', 'Anonymous Proxy'),
(NULL, 'SY', 'Syrian Arab Republic'),
(NULL, 'CY', 'Cyprus'),
(NULL, 'CZ', 'Czech Republic'),
(NULL, 'IQ', 'Iraq'),
(NULL, 'TR', 'Turkey'),
(NULL, 'RO', 'Romania'),
(NULL, 'LB', 'Lebanon'),
(NULL, 'HU', 'Hungary'),
(NULL, 'GE', 'Georgia'),
(NULL, 'BR', 'Brazil'),
(NULL, 'AZ', 'Azerbaijan'),
(NULL, 'A2', 'Satellite Provider'),
(NULL, 'PS', 'Palestinian Territory'),
(NULL, 'LT', 'Lithuania'),
(NULL, 'OM', 'Oman'),
(NULL, 'SK', 'Slovakia'),
(NULL, 'RS', 'Serbia'),
(NULL, 'FI', 'Finland'),
(NULL, 'IS', 'Iceland'),
(NULL, 'BG', 'Bulgaria'),
(NULL, 'SI', 'Slovenia'),
(NULL, 'MD', 'Moldov'),
(NULL, 'MK', 'Macedonia'),
(NULL, 'LI', 'Liechtenstein'),
(NULL, 'JE', 'Jersey'),
(NULL, 'PL', 'Poland'),
(NULL, 'HR', 'Croatia'),
(NULL, 'BA', 'Bosnia and Herzegovina'),
(NULL, 'EE', 'Estonia'),
(NULL, 'LV', 'Latvia'),
(NULL, 'JO', 'Jordan'),
(NULL, 'KG', 'Kyrgyzstan'),
(NULL, 'RE', 'Reunion'),
(NULL, 'IE', 'Ireland'),
(NULL, 'LY', 'Libya'),
(NULL, 'LU', 'Luxembourg'),
(NULL, 'AM', 'Armenia'),
(NULL, 'VG', 'Virgin Island'),
(NULL, 'YE', 'Yemen'),
(NULL, 'BY', 'Belarus'),
(NULL, 'GI', 'Gibraltar'),
(NULL, 'MQ', 'Martinique'),
(NULL, 'PA', 'Panama'),
(NULL, 'DO', 'Dominican Republic'),
(NULL, 'GU', 'Guam'),
(NULL, 'PR', 'Puerto Rico'),
(NULL, 'VI', 'Virgin Island'),
(NULL, 'MN', 'Mongolia'),
(NULL, 'NZ', 'New Zealand'),
(NULL, 'SG', 'Singapore'),
(NULL, 'ID', 'Indonesia'),
(NULL, 'NP', 'Nepal'),
(NULL, 'PG', 'Papua New Guinea'),
(NULL, 'PK', 'Pakistan'),
(NULL, 'AP', 'Asia/Pacific Region'),
(NULL, 'BS', 'Bahamas'),
(NULL, 'LC', 'Saint Lucia'),
(NULL, 'AR', 'Argentina'),
(NULL, 'BD', 'Bangladesh'),
(NULL, 'TK', 'Tokelau'),
(NULL, 'KH', 'Cambodia'),
(NULL, 'MO', 'Macau'),
(NULL, 'MV', 'Maldives'),
(NULL, 'AF', 'Afghanistan'),
(NULL, 'NC', 'New Caledonia'),
(NULL, 'FJ', 'Fiji'),
(NULL, 'WF', 'Wallis and Futuna'),
(NULL, 'QA', 'Qatar'),
(NULL, 'AL', 'Albania'),
(NULL, 'BZ', 'Belize'),
(NULL, 'UZ', 'Uzbekistan'),
(NULL, 'KW', 'Kuwait'),
(NULL, 'ME', 'Montenegro'),
(NULL, 'PE', 'Peru'),
(NULL, 'BM', 'Bermuda'),
(NULL, 'CW', 'Curacao'),
(NULL, 'CO', 'Colombia'),
(NULL, 'VE', 'Venezuela'),
(NULL, 'CL', 'Chile'),
(NULL, 'EC', 'Ecuador'),
(NULL, 'ZA', 'South Africa'),
(NULL, 'IM', 'Isle of Man'),
(NULL, 'BO', 'Bolivia'),
(NULL, 'GG', 'Guernsey'),
(NULL, 'MT', 'Malta'),
(NULL, 'TJ', 'Tajikistan'),
(NULL, 'SC', 'Seychelles'),
(NULL, 'BH', 'Bahrain'),
(NULL, 'EG', 'Egypt'),
(NULL, 'ZW', 'Zimbabwe'),
(NULL, 'LR', 'Liberia'),
(NULL, 'KE', 'Kenya'),
(NULL, 'GH', 'Ghana'),
(NULL, 'NG', 'Nigeria'),
(NULL, 'TZ', 'Tanzani'),
(NULL, 'ZM', 'Zambia'),
(NULL, 'MG', 'Madagascar'),
(NULL, 'AO', 'Angola'),
(NULL, 'NA', 'Namibia'),
(NULL, 'CI', 'Cote D''Ivoire'),
(NULL, 'SD', 'Sudan'),
(NULL, 'CM', 'Cameroon'),
(NULL, 'MW', 'Malawi'),
(NULL, 'GA', 'Gabon'),
(NULL, 'ML', 'Mali'),
(NULL, 'BJ', 'Benin'),
(NULL, 'TD', 'Chad'),
(NULL, 'BW', 'Botswana'),
(NULL, 'CV', 'Cape Verde'),
(NULL, 'RW', 'Rwanda'),
(NULL, 'CG', 'Congo'),
(NULL, 'UG', 'Uganda'),
(NULL, 'MZ', 'Mozambique'),
(NULL, 'GM', 'Gambia'),
(NULL, 'LS', 'Lesotho'),
(NULL, 'MU', 'Mauritius'),
(NULL, 'MA', 'Morocco'),
(NULL, 'DZ', 'Algeria'),
(NULL, 'GN', 'Guinea'),
(NULL, 'CD', 'Cong'),
(NULL, 'SZ', 'Swaziland'),
(NULL, 'BF', 'Burkina Faso'),
(NULL, 'SL', 'Sierra Leone'),
(NULL, 'SO', 'Somalia'),
(NULL, 'NE', 'Niger'),
(NULL, 'CF', 'Central African Republic'),
(NULL, 'TG', 'Togo'),
(NULL, 'BI', 'Burundi'),
(NULL, 'GQ', 'Equatorial Guinea'),
(NULL, 'SS', 'South Sudan'),
(NULL, 'SN', 'Senegal'),
(NULL, 'MR', 'Mauritania'),
(NULL, 'DJ', 'Djibouti'),
(NULL, 'KM', 'Comoros'),
(NULL, 'IO', 'British Indian Ocean Territory'),
(NULL, 'TN', 'Tunisia'),
(NULL, 'GL', 'Greenland'),
(NULL, 'VA', 'Holy See (Vatican City State)'),
(NULL, 'CR', 'Costa Rica'),
(NULL, 'KY', 'Cayman Islands'),
(NULL, 'JM', 'Jamaica'),
(NULL, 'GT', 'Guatemala'),
(NULL, 'MH', 'Marshall Islands'),
(NULL, 'AQ', 'Antarctica'),
(NULL, 'BB', 'Barbados'),
(NULL, 'AW', 'Aruba'),
(NULL, 'MC', 'Monaco'),
(NULL, 'AI', 'Anguilla'),
(NULL, 'KN', 'Saint Kitts and Nevis'),
(NULL, 'GD', 'Grenada'),
(NULL, 'PY', 'Paraguay'),
(NULL, 'MS', 'Montserrat'),
(NULL, 'TC', 'Turks and Caicos Islands'),
(NULL, 'AG', 'Antigua and Barbuda'),
(NULL, 'TV', 'Tuvalu'),
(NULL, 'PF', 'French Polynesia'),
(NULL, 'SB', 'Solomon Islands'),
(NULL, 'VU', 'Vanuatu'),
(NULL, 'ER', 'Eritrea'),
(NULL, 'TT', 'Trinidad and Tobago'),
(NULL, 'AD', 'Andorra'),
(NULL, 'HT', 'Haiti'),
(NULL, 'SH', 'Saint Helena'),
(NULL, 'FM', 'Micronesi'),
(NULL, 'SV', 'El Salvador'),
(NULL, 'HN', 'Honduras'),
(NULL, 'UY', 'Uruguay'),
(NULL, 'LK', 'Sri Lanka'),
(NULL, 'EH', 'Western Sahara'),
(NULL, 'CX', 'Christmas Island'),
(NULL, 'WS', 'Samoa'),
(NULL, 'SR', 'Suriname'),
(NULL, 'CK', 'Cook Islands'),
(NULL, 'KI', 'Kiribati'),
(NULL, 'NU', 'Niue'),
(NULL, 'TO', 'Tonga'),
(NULL, 'TF', 'French Southern Territories'),
(NULL, 'YT', 'Mayotte'),
(NULL, 'NF', 'Norfolk Island'),
(NULL, 'BN', 'Brunei Darussalam'),
(NULL, 'TM', 'Turkmenistan'),
(NULL, 'PN', 'Pitcairn Islands'),
(NULL, 'SM', 'San Marino'),
(NULL, 'AX', 'Aland Islands'),
(NULL, 'FO', 'Faroe Islands'),
(NULL, 'SJ', 'Svalbard and Jan Mayen'),
(NULL, 'CC', 'Cocos (Keeling) Islands'),
(NULL, 'NR', 'Nauru'),
(NULL, 'GS', 'South Georgia and the South Sandwich Islands'),
(NULL, 'UM', 'United States Minor Outlying Islands'),
(NULL, 'GW', 'Guinea-Bissau'),
(NULL, 'PW', 'Palau'),
(NULL, 'AS', 'American Samoa'),
(NULL, 'BT', 'Bhutan'),
(NULL, 'GF', 'French Guiana'),
(NULL, 'GP', 'Guadeloupe'),
(NULL, 'MF', 'Saint Martin'),
(NULL, 'VC', 'Saint Vincent and the Grenadines'),
(NULL, 'PM', 'Saint Pierre and Miquelon'),
(NULL, 'BL', 'Saint Barthelemy'),
(NULL, 'DM', 'Dominica'),
(NULL, 'ST', 'Sao Tome and Principe'),
(NULL, 'KP', 'Kore'),
(NULL, 'FK', 'Falkland Islands (Malvinas)'),
(NULL, 'MP', 'Northern Mariana Islands'),
(NULL, 'TL', 'Timor-Leste'),
(NULL, 'BQ', 'Bonair'),
(NULL, 'MM', 'Myanmar'),
(NULL, 'NI', 'Nicaragua'),
(NULL, 'SX', 'Sint Maarten (Dutch part)'),
(NULL, 'GY', 'Guyana'),
(NULL, 'LA', 'Lao People''s Democratic Republic'),
(NULL, 'CU', 'Cuba'),
(NULL, 'ET', 'Ethiopia');